config/routes.rb
Rails.application.routes.draw do
 
  root 'home#index'
  devise_for :users

  resources :home
  resources :todos
  resources :bucket_lists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket_list.rb
class BucketList < ApplicationRecord
  belongs_to :user
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos, dependent: :destroy
  has_many :bucket_lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!


protected
def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
end
 
end

app/controllers/bucket_lists_controller.rb
class BucketListsController < ApplicationController
  before_action :set_bucket_list, only: [:show, :edit]

  def index
    @bucket_lists = BucketList.all
  end

  def show
  end

  def new
    @bucket_list = BucketList.new
    render partial: "form"
  end

  def create
    #inspect params here
      #pinding.pry
    @bucket_list = BucketList.new(bucket_list_params)
    
    if @bucket_list.save
     redirect_to bucket_list_path
    else
      render :new
    end
    end

  def edit
  end

def destroy
  
end

private

def bucket_list_params
params.require(:bucket_list).permit(:name, :location)
end

def set_bucket_list
  @bucket_list = BucketList.find(params[:id])
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = current_user.todos
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = current_user.todos.new(todo_params)
    if @todo.save
      redirect_to todos_path
    else
      render :new 
    end
  end

  def edit
  end

  def update
    if @todo.update(account_params)
      redirect_to todos_path
    else
      render :edit
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_path(@todo)
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :item)
  end

  def set_todo
    @todo = current_user.todos.find(params[:id])
  end



  
end

app/helpers/application_helper.rb
module ApplicationHelper
 
end

app/helpers/bucket_lists_helper.rb
module BucketListsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/bucket_lists/_form.html.erb
<h1><%= @bucket_list.id ? 'Edit List Item' : 'Create List Item' %></h1>
<hr />
<%= form_for @bucket_list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.label :location %>
  <%= f.text_field :location, required: true %>
  <%= f.submit %>
<% end %>

app/views/bucket_lists/edit.html.erb
<h1>BucketLists#edit</h1>
<p>Find me in app/views/bucket_lists/edit.html.erb</p>

app/views/bucket_lists/index.html.erb
<h1>Bucket List!</h1>
<h3>This is wthe list of things you want to do before you die</h3>
<br />
<%= link_to "View Bucket List", bucket_lists_path, class:"btn btn-primary"%>
<%= link_to "Go Back", home_index_path, class:"btn btn-primary"%>
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>

<<ul>
  <% @bucket_lists.each do |bucket_list| %>
    <li><%= link_to bucket_list.name, bucket_list %></li>
  <% end %>
</ul>

app/views/bucket_lists/new.html.erb
<h1>BucketLists#new</h1>
<p>Find me in app/views/bucket_lists/new.html.erb</p>

app/views/bucket_lists/show.html.erb
<<ul>
  <% @bucket_lists.each do |bucket_list| %>
    <li><%= link_to bucket_list.name, bucket_list %></li>
  <% end %>
</ul>

app/views/home/index.html.erb
<h2>Welcome, <%= current_user.first_name%></h2>
<br>
<br>
<br>
<p> Checkout your list below</p>
<%= link_to "To-Do List", todos_path, class:"btn btn-primary" %>
<%= link_to "Buckets List", bucket_lists_path, class:"btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= button_to "Log Out", destroy_user_session_path, method: :delete %>
     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <div class="container">
    <%= yield %>









</div>




<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </body>
</html>

app/views/todos/edit.html.erb
<h1>Todos#edit</h1>
<p>Find me in app/views/todos/edit.html.erb</p>

app/views/todos/index.html.erb
<h2>Hey, there <%= current_user.first_name %></h2>
<hr />
<%= link_to "Add To-Do", new_todo_path, class:"btn btn-success" %>
<h3>You're To-Do list!</h3>
<ul>
  <% @todos.each do |todo| %>
    <li>
      <%=link_to todo.name,todo %> : <%= todo.item%>
    </li>
  <% end %>



  <%= link_to "Back", root_path, class:"btn btn-primary" %>
</ul>

app/views/todos/new.html.erb
<h1>Add To-Do</h1>
<%= form_with(model: @todo, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name of Todo" %>
  </div>
   <div class="field">
    <%= f.label :item %>
    <%= f.text_field :item, required: true, placeholder: "Item on the Todo" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/todos/show.html.erb
<h1>Hello, <%= current_user.first_name %></h1>
<hr />
<h4>Here is the <%= @todo.name %></h4>
<br>
<h6>Item on your Todo: </h6>
<br>
<%=@todo.item%>
<br>


<br>
<br>
<%= link_to "Back", todos_path, class:"btn btn-primary" %>
<br>
<br>
<%= link_to 'Delete Todo', @todo, method: :delete, class: "btn btn-danger" %>